import React from 'react';

const PromotionThree = () => {
    return (
        <>
            <div className="promo-section px-6 md:px-24 pt-24">
                <p className='text-left text-2xl md:text-4xl mb-24 font-bold leading-normal'>
                    You will get all the advantages that come with professional landing page design services
                </p>
                <div className="promo-content flex flex-col items-start justify-center gap-4">
                    <p>By working with our professional landing page design team you'll have access to several benefits:</p>
                    <ol>
                        <li>Receive a custom conversion strategy and design for every landing page.</li>
                        <li> We will provide a personal account manager</li>
                        <li>Mobile, desktop, and tablet responsive landing pages for your users.</li>
                        <li>We will set up conversion tracking codes on all your landing pages.</li>
                        <li>Track calls generated by your landing pages in one convenient place.</li>
                        <li>Integrations of lead forms an databases</li>
                        <li>And much more.</li>
                    </ol>
                    <p>At Muscled we give you a complete solution to landing pages.</p>
                    <p>Our design, development, and marketing team closely work together to design attractive and striking user friendly landing pages with top of the line copy and conversions. In addition your personal account manager makes sure any of your questions and messages are answered quickly.</p>

                    <p>That's why we have such a high client recommendation score.</p>
                </div>
            </div>   
        </>
    );
};

export default PromotionThree;

